config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
end
  root to: "pages#home"
  get 'about', to: 'pages#about'
  resources :communicates, only: :create
  get 'communicate-with-us', to: 'communicates#new', as: 'new_communicate'
end

app/models/Subscription.rb
class Subscription < ActiveRecord::Base 
   has_many :users
end	

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/communicate.rb
class Communicate < ApplicationRecord
	# Communicate form validations
	validates :name, presence: true
	validates :email, presence: true
	validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :subscription
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/communicates_controller.rb
class CommunicatesController < ApplicationController
  before_action :set_communicate, only: %i[ show edit update destroy ]

  # GET /communicates or /communicates.json
  def index
    @communicates = Communicate.all
  end

  # GET /communicates/1 or /communicates/1.json
  def show
  end

  # GET /communicates/new
  def new
    @communicate = Communicate.new
  end

  # GET /communicates/1/edit
  def edit
  end

  # POST /communicates or /communicates.json
  def create
    @communicate = Communicate.new(communicate_params)

    # respond_to do |format|
    #   if @communicate.save
    #     format.html { redirect_to new_communicate_path, notice: "Message sent." }
    #     format.json { render :show, status: :created, location: @communicate }
    #   else
    #     format.html { render :new, status: :unprocessable_entity, notice: "Error occured." }
    #     format.json { render json: @communicate.errors, status: :unprocessable_entity }
    #   end
      if @communicate.save
        name = params[:communicate][:name]
        email = params[:communicate][:email]
        body = params[:communicate][:comment]
        CommunicateMailer.communicate_email(name, email, body).deliver
        flash[:success] = "Message sent"
        redirect_to new_communicate_path
      else
        flash[:danger] = @communicate.errors.full_messages.join(", ")
        redirect_to new_communicate_path 
      # end   
    end
  end

  # PATCH/PUT /communicates/1 or /communicates/1.json
  def update
    respond_to do |format|
      if @communicate.update(communicate_params)
        format.html { redirect_to communicate_url(@communicates), notice: "Communicate was successfully updated." }
        format.json { render :show, status: :ok, location: @communicate }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @communicate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communicates/1 or /communicates/1.json
  def destroy
    @communicate.destroy

    respond_to do |format|
      format.html { redirect_to communicates_url, notice: "Communicate was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_communicate
      @communicate = Communicate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def communicate_params
      params.require(:communicate).permit(:name, :email, :comment)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
		@basic_subscription = Subscription.find(1)
		@pro_subscription = Subscription.find(2)
	end

	def about
	end
end		

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/communicates_helper.rb
module CommunicatesHelper
end

app/views/communicates/_communicate.html.erb
<div id="<%= dom_id communicate %>">
  <p>
    <strong>Name:</strong>
    <%= communicate.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= communicate.email %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= communicate.comment %>
  </p>

</div>

app/views/communicates/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
<%= form_with(model: communicate) do |form| %>
  <% if communicate.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(communicate.errors.count, "error") %> prohibited this communicate from being saved:</h2>

      <ul>
        <% communicate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :comment, style: "display: block" %>
    <%= form.text_area :comment, class: 'form-control' %>
  </div>
  <br/>
  <div class="form-group">
    <%= form.submit 'Submit', class: 'btn btn-primary' %>
  </div>
  <br/>
  <br/>
<% end %>
    </div>
  </div>
</div>

app/views/communicates/edit.html.erb
<!-- <h1>Editing communicate</h1>

<%= render "form", communicate: @communicate %>

<br>

<div>
  <%= link_to "Show this communicate", @communicate %> |
  <%= link_to "Back to communicates", communicates_path %>
</div>
 -->

app/views/communicates/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Communicates</h1>

<div id="communicates">
  <% @communicates.each do |communicate| %>
    <%= render communicate %>
    <p>
      <%= link_to "Show this communicate", communicate %>
    </p>
  <% end %>
</div>

<%= link_to "New communicate", new_communicate_path %>

app/views/communicates/new.html.erb
<div class="container">
  <br/>
  <div class="row">
<h3 class="text-center">Contact Us</h3>

<%= render "form", communicate: @communicate %>

<br>
<br/>

<div>
  <%= link_to "Back to Home", root_path %>
</div>
</div>
</div>

app/views/communicates/show.html.erb
<!-- <p style="color: green"><%= notice %></p>

<%= render @communicate %>

<div>
  <%= link_to "Edit this communicate", edit_communicate_path(@communicate) %> |
  <%= link_to "Back to communicates", communicates_path %>

  <%= button_to "Destroy this communicate", @communicate, method: :delete %>
</div>
 -->

app/views/contacts/new.html.erb
<div class="container">
	<br/>
	<div class="row">
		
	<div class="col-md-4">
      <%= flash[:notice] %>
    <h3 class="text-center">Contact Us</h3>

    <%= form_for(model: contact) do |f| %>
    <div class="form-group">
    	<%= f.label :name  %>
        <%= f.text_field :name, class: 'form-control' %>
    </div>
    <br />
     <div class="form-group">
    	<%= f.label :email %>
        <%= f.text_field :email,class: 'form-control' %>
    </div>
    <br />
     <div class="form-group">
    	 <%= f.label :comments %>
        <%= f.text_area :comments, class: 'form-control' %>
    </div>      
     <br />
        <%= f.submit 'Submit', class: 'btn btn-default' %>

    <% end %>

    </div>
  </div>
</div>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Membership App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;700;800&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_include_tag "https://js.stripe.com/v3/", type: 'text/javascript' %>
     
    <%= javascript_pack_tag 'application' %>
    <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
   
  </head>

  <body>

  <!--Navbar -->
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
      
        <%= link_to "/", class: "navbar-brand" do %>
             <i class="fa fa-group"></i>
              DevMatch
        <% end %>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">

            <ul class="navbar-nav">
              <li class="nav-item">
                <!-- <a class="nav-link active" aria-current="page" href="/">Home</a> -->
                  <%= link_to "Home", root_path, class: "nav-link active" %>
              </li>
              <li class="nav-item">
                <%= link_to "About", about_path, class: "nav-link"%>
              </li>
               <li class="nav-item">
                <%= link_to "Contact Us", new_communicate_path, class: "nav-link"%>
              </li>
              
            </ul>
            <div class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-light navbar-btn" %>
<% else %>
  <%= link_to "Log In", new_user_session_path, class: "btn btn-light navbar-btn", style: "margin-right: 10px" %>
<% end %>
</div>
          </div>
      </div>
    </nav>
<!--Navbar end -->
      <div class="container">
         <% flash.each do |type, msg| %>
             <%= content_tag :div, msg, class: "alert alert-#{type}"  %>
          <% end %> 
      </div>    
      <%= yield %>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous">  
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous">
    </script>


  </body>
</html>

app/views/pages/about.html.erb
<div class="container text-center">
	<br/>
<h1>About Page</h1>
   <p>We are DevMatch. Our company focuses on creating an exclusive community for developer and entrepreneur to meet.</p>
</div>

app/views/pages/home.html.erb
<div class='home-callout text-center container-fluid'>
   <h1>Welcome to DevMatch.</h1> 
   <h3>A membership site where entrepreneur can meet developers.</h3>
</div>
<div class="container home-signup-link">
   <div class="row">
      <div class="col-md-6">
         <div class="text-center subscription-container">
            <h2 class="text-center subscription-heading">Basic Membership</h2>
            <h4>Sign up for free and get basic access to the community</h4>
            <br/>
            <%= link_to 'Sign up to Basic Subscription', new_user_registration_path(subscription: @basic_subscription.id), class: 'btn btn-primary btn-lg' %>
         </div>
      </div>

      <div class="col-md-6">
         <div class="text-center subscription-container">
            <h2 class="text-center subscription-heading">Pro Membership</h2>
            <h4>Sign up for the pro account for $10/month and get access to the community and contact information!</h4>
           
              <%= link_to 'Sign up to Pro Subscription', new_user_registration_path(subscription: @pro_subscription.id), class: 'btn btn-success btn-lg' %>
         </div>
      </div>   
   </div>  
</div>